MAINT: Don't use the backtrace from backward.hpp
Since it seems to break on musllinux...

https://github.com/d-SEAMS/PydSEAMSlib/actions/runs/10565220956/job/29269283061?pr=21#step:4:1135

        In file included from ../subprojects/seams-core/src/backward.cpp:40:
        ../subprojects/seams-core/src/include/external/backward.hpp:261:10: fatal error: execinfo.h: No such file or directory
          261 | #include <execinfo.h>
              |          ^~~~~~~~~~~~